### ISSUE TITLE
Community,Map, & Select Topics enhancement

### ISSUE THREAD

**Issue by IDEddy** [ejricahuerta/HopeLine#77]
- **Select Topics Page:** Emile said that he wanted less wording or something more straight forward in the select topics page when a client wants to talk to a mentor.

- **Community page:** just needs enhancement. A few descriptions about what we're referencing to instead of dummy values.
- **Map Page:** Search function,map and terrain filter is cut out.Map needs to be resized. Filtering needs to be completed.

**Comment by ejricahuerta** [comment]
@IDEddy 
These must be implemented:
- Toggle on an off for location buttons.
- A button to clear the markers.
- User should be able to do a custom location search
