### ISSUE TITLE
Post-midterm review updates

### ISSUE THREAD

**Issue by IDEddy** [ejricahuerta/HopeLine#82]
Overall, from what we have discussed and gathered on the midterm review we need major updates to how a user would communicate with the mentor and it's ease of access. These need to be done before second evaluation(few days)!
Please feel free to edit this!. This issue is the keep track of the issues from midterm evaluation. 
More !  means more severity!

**Minor updates needed:**
-Character limit to username. If username has no limit then the navbar would be adjusted to fit the name. Limit needs to be updated to prevent navbar form being adjusted.(!) -Done
-Dummy values and lorem ipsum need to be filled.(!) - Done
-Get rid of the extra filter checkbox after clicking submit to talk to mentor. This is related to the major update below.(!!)  - done
-Pictures need to be changed to avoid copyright.(!!) - Done
-Android map location reset?(!) - done?

**Major updates required:**

**-Website needs to be more "client friendly". Basically, we need to redesign or update a portion of the website to make it a less of a hassle for the user. This may include talk to mentor page, index(#53),and all the other pages(#77,#52,#54) that are related to the user communicating with mentor.(!!!!!)**-in-progress
-Android and IOS development.(!!!!) - in-progress 
-Something about the tokens for live chat? Ease of access?(!!!)-Done
-Web-rtc video and audio network.(!!!)-in-progress

**Comment by ejricahuerta** [comment]
Closing all past issues.
